# playerRole=(mazziere,puntatore,cambiatore,buio,comtrobuio,over,eliminato)
# modalitaIncremento=(nullo,a tempo,giri,eliminazioneGiocatore)
# tipoApertura=(normale,di parola,nessuno aprì)
# barare=(spiare carte,specchio,occhiali raggi x,passare una carta,fare segni,imbrogliare col mazzo,non tagliare,prendere da sotto)
# sbagliare=(parlare prima del turno, sbagliare)
# reactions(smoke cigarette, etc.)